name: integration-tests-back

on: push

jobs:
    check_if_files_changed_in_back:
        runs-on: ubuntu-latest
        outputs:
            back_changed: ${{steps.check_file_changed.outputs.docs_changed}}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 2
            - shell: pwsh
              id: check_file_changed
              run: |
                  $diff = git diff --name-only HEAD^ HEAD
                  $SourceDiff = $diff | Where-Object { $_ -match '^back/'}
                  $HasDiff = $SourceDiff.Length -gt 0

                  Write-Host "::set-output name=docs_changed::$HasDiff"
    test-back:
        runs-on: ubuntu-latest
        needs: [check_if_files_changed_in_back]
        if: needs.check_if_files_changed_in_back == 'True'
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Go to back and run tests
              run: npm run integration-test
    docker:
        needs: test-back
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  push: true
                  context: '{{defaultContext}}:back'
                  tags: holmeseh/karims-wilders-book-back:latest
